version: "3.9"

services:
  bookmarket:
    image: bookmarket:latest
    container_name: bookmarket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-cache
    env_file:
      - .env
    volumes:
      # Gradle 캐시를 로컬에 매핑하여 빌드 속도 개선
      - ~/.gradle:/home/gradle/.gradle
    networks:
      - backend

  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
